version: '3.4'

volumes:
  nethermind_data:
  lighthouse_data:

services:
  nethermind:
    image: nethermindeth/nethermind:eip-4844
    ports:
      - '8545:8545'
      - '30303:30303'
    volumes:
      - 'nethermind_data:/db'
      - type: bind
        source: ./geth/jwtsecret
        target: /config/jwtsecret
      - type: bind
        source: ./nethermind/config.json
        target: /nethermind/configs/mainnet.cfg
      - type: bind
        source: ./nethermind/genesis.json
        target: /genesis.json

  lighthouse:
    build:
      context: ./lighthouse
      dockerfile: Dockerfile.lighthouse
    ports:
      - "5052:5052"
      - "8000:8000"
      - "9000:9000"
    command: >
      lighthouse bn
      --network eip4844
      --datadir /data
      --execution-jwt /config/jwtsecret
      --execution-endpoint http://nethermind:8551
      --debug-level debug
      --trusted-setup-file /config/trusted_setup.txt
      --libp2p-addresses /ip4/34.121.33.53/tcp/13000/p2p/16Uiu2HAkwy4MJBLsCvmuPwrfVX9GqNiGeppshnsbn2BgKskCtRDE,/ip4/34.122.190.151/tcp/13000/p2p/16Uiu2HAmHd6WSHUEB7SrxdDR8dPVLTJqkzgPGbriej15udyQZugY,/ip4/34.123.117.254/tcp/13000/p2p/16Uiu2HAmSLVoxaR1ztHqBjezWFSvFa3HeTWPZNswfS4aMWob59L6 
      --http
    volumes:
      - lighthouse_data:/data
      - type: bind
        source: ./lighthouse/trusted_setup.txt
        target: /config/trusted_setup.txt
      - type: bind
        source: ./geth/jwtsecret
        target: /config/jwtsecret